// post-format.mjs — pure helpers shared by the brain (drafting/validation) and
// the poster (event assembly). Everything here is deterministic and unit-tested
// (post-format.test.mjs); neither side should hand-roll this wire format.
//
// The three house rules every outbound post enforces (Director's standing
// instruction): a nave.pub link, a relevant graphic, appropriate hashtags.

// A nave.pub link counts if ANY nave.pub URL is present (deep links to public
// app subdomains satisfy it — nvoy.nave.pub, notegate.nave.pub, …).
// The lookahead pins the host boundary: nave.pub must be the WHOLE host tail
// (nave.pubx.com and nave.pub.evil.com both fail it).
const NAVE_LINK_RE = /https?:\/\/(?:[a-z0-9-]+\.)*nave\.pub(?![\w.-])(?:\/\S*)?/i

export const SITE_URL = 'https://nave.pub'

export function hasSiteLink(text) {
  return NAVE_LINK_RE.test(String(text || ''))
}

// Append the site link on its own line unless some nave.pub URL is already in
// the text. Idempotent.
export function ensureSiteLink(text, url = SITE_URL) {
  const t = String(text || '').trimEnd()
  return hasSiteLink(t) ? t : `${t}\n\n${url}`
}

// Flatten RSS bodies and README markdown into readable text for prompt excerpts.
// Strips script/style, comments, markdown images/badges and any remaining tags;
// decodes the common entities; collapses whitespace. Deliberately lossy — the
// gist, not fidelity. Shared so the brain and the scribe can't drift apart.
export function htmlToText(html) {
  return String(html || '')
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&#39;|&rsquo;|&apos;/g, "'").replace(/&quot;|&ldquo;|&rdquo;/g, '"').replace(/&hellip;/g, '\u2026')
    .replace(/&#[xX]([0-9a-fA-F]+);/g, (_, h) => { try { return String.fromCodePoint(parseInt(h, 16)) } catch { return ' ' } })
    .replace(/&#(\d+);/g, (_, n) => { try { return String.fromCodePoint(+n) } catch { return ' ' } })
    .replace(/\s+/g, ' ').trim()
}

// The APEX specifically. A subdomain deep-link does NOT satisfy this — the
// standing rule is that nave.pub itself is always referenced, and any app the
// post actually names carries its own link IN ADDITION.
const APEX_RE = /https?:\/\/nave\.pub(?![\w.-])(?:\/\S*)?/i

export function hasApexLink(text) {
  return APEX_RE.test(String(text || ''))
}

// Public app surfaces only. The gated hosts (cockpit, console) and anything
// still in design (Nops) are deliberately absent — a public post never points
// at a sovereign-only gate. Nact and its runtime Nactor share one destination.
export const APP_LINKS = {
  nvoy: 'https://nvoy.nave.pub',
  nact: 'https://nact.nave.pub',
  nactor: 'https://nact.nave.pub',
  nontact: 'https://nontact.nave.pub',
  nvelope: 'https://nvelope.nave.pub',
  notegate: 'https://notegate.nave.pub',
  ntrigue: 'https://ntrigue.nave.pub',
  nherit: 'https://nherit.nave.pub',
  nscope: 'https://nscope.nave.pub',
  noir: 'https://noir.nave.pub',
  ngage: 'https://ngage.nave.pub',
  'warm.contact': 'https://warm.contact',
}

// Which app destinations a post actually names. Word-boundary matched, so
// "Nactor" doesn't trip the bare "Nact" rule and vice versa; deduped by URL.
export function mentionedApps(text) {
  const t = String(text || '')
  const urls = new Set()
  for (const [name, url] of Object.entries(APP_LINKS)) {
    if (new RegExp(`\\b${name.replace(/\./g, '\\.')}\\b`, 'i').test(t)) urls.add(url)
  }
  return [...urls]
}

// Append the link for every app the post names that isn't already linked.
// Idempotent.
export function ensureAppLinks(text) {
  let t = String(text || '').trimEnd()
  for (const url of mentionedApps(t)) if (!t.includes(url)) t += `\n${url}`
  return t
}

// The full link rule: nave.pub is ALWAYS present, and any app the post names
// carries its own link too. This is what the drafting surfaces enforce.
export function ensureLinks(text) {
  const t = String(text || '').trimEnd()
  return ensureAppLinks(hasApexLink(t) ? t : `${t}\n\n${SITE_URL}`)
}

// The Director's standing AI-assistance disclosure (his wording, 2026-07-23).
// One line, at the very bottom of every post. `ensureDisclosure` NORMALIZES:
// it strips any prior Claude/AI attribution the model may have emitted on its
// own ("Generated by Claude Code", "→ claude.ai", "via Claude", etc.) so there
// is never a double disclosure, then appends exactly this line. Idempotent.
export const DISCLOSURE = 'Some of the content drafting within my posts is assisted by Claude Code (https://claude.com/claude-code).'
// Lines treated as a pre-existing AI attribution to replace (model-emitted or
// an earlier disclosure). Matched whole-line, case-insensitive; tolerates
// surrounding markdown emphasis.
const AI_ATTRIB_RE = /^\s*[_*]*\s*(some of the content[\s\S]*?claude.*|generated (by|with) claude.*|drafted (by|with) claude.*|(written|assisted|co-?written) (by|with) claude.*|.*→\s*claude\.ai.*|via claude.*)\s*[_*]*\s*$/i
export function ensureDisclosure(text) {
  const kept = String(text || '').split('\n')
    .filter(l => !AI_ATTRIB_RE.test(l))
    .join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()
  return `${kept}\n\n${DISCLOSURE}`
}

// Hashtags as clients index them: lowercase, no '#', deduped, in order of
// appearance. Matches letters/digits/underscore (the common client tokenizer).
export function extractHashtags(text) {
  const seen = new Set()
  for (const m of String(text || '').matchAll(/(?:^|\s)#([\p{L}\p{N}_]+)/gu)) {
    const tag = m[1].toLowerCase()
    if (!seen.has(tag)) seen.add(tag)
  }
  return [...seen]
}

// Guarantee at least one hashtag; if the draft has none, add the ecosystem tag
// on its own line (before any trailing link line, after the prose).
export function ensureHashtags(text, fallback = 'nave') {
  const t = String(text || '').trimEnd()
  if (extractHashtags(t).length) return t
  if (!hasSiteLink(t)) return `${t}\n\n#${fallback}`
  // Keep the link as the final line: insert the tag line above the first line
  // that contains the nave.pub URL.
  const lines = t.split('\n')
  const i = lines.findIndex(l => NAVE_LINK_RE.test(l))
  lines.splice(i, 0, `#${fallback}`, '')
  return lines.join('\n').replace(/\n{3,}/g, '\n\n')
}

// Final note content: prose (already carrying hashtags + link) with the image
// URL as the last line — clients render a trailing media URL inline.
export function composeContent(text, imageUrl) {
  const t = String(text || '').trimEnd()
  return imageUrl ? `${t}\n\n${imageUrl}` : t
}

const IMAGE_MIME = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp' }

// NIP-92 imeta tag for an image URL (space-delimited key/value strings).
export function imetaTag(url, alt) {
  const ext = (String(url).split('?')[0].match(/\.(\w+)$/) || [])[1]?.toLowerCase()
  const parts = [`url ${url}`]
  if (IMAGE_MIME[ext]) parts.push(`m ${IMAGE_MIME[ext]}`)
  if (alt) parts.push(`alt ${alt}`)
  return ['imeta', ...parts]
}

// Tags for a kind-1: NIP-10 threading (when replying), NIP-92 imeta (when an
// image rides along), and a lowercase `t` tag per hashtag in the content so
// hashtag feeds actually surface the note.
//
// `parent` is the event being replied to, if the poster could fetch it:
//   - with a parent that is itself a reply (has an e-root tag): proper marked
//     threading — root stays root, parent becomes the 'reply' marker;
//   - with a top-level parent: parent IS the root;
//   - without a parent event (fetch failed): fall back to the old behavior,
//     e-tag the id as root so the thread link at least holds.
// The p tag on the parent author is what makes the reply NOTIFY them — a reply
// nobody sees is not engagement.
export function buildTags({ content, imageUrl, imageAlt, replyTo, parent }) {
  const tags = []
  if (replyTo) {
    if (parent && parent.id === replyTo) {
      const rootId = (parent.tags?.find(t => t[0] === 'e' && t[3] === 'root') || [])[1]
      if (rootId && rootId !== parent.id) {
        tags.push(['e', rootId, '', 'root'], ['e', parent.id, '', 'reply'])
      } else {
        tags.push(['e', parent.id, '', 'root'])
      }
      if (parent.pubkey) tags.push(['p', parent.pubkey])
    } else {
      tags.push(['e', replyTo, '', 'root'])
    }
  }
  if (imageUrl) tags.push(imetaTag(imageUrl, imageAlt))
  for (const t of extractHashtags(content)) tags.push(['t', t])
  return tags
}
